version: '3'

services:

    consulserver:
      image: progrium/consul:latest
      environment:
        SERVICE_TAGS: consul servers
      hostname: consulserver
      ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "53:53"
      - '8600:8600'
      command: -server -ui-dir /ui -data-dir /tmp/consul -bootstrap-expect 1

    user_service:
      image: user_service
      environment:
       - ASPNETCORE_URLS=http://0.0.0.0:80
       - ConsulUrl=http://consulserver:8500
       - RegisterServerUrl=http://user_service
       - RegisterServiceName=user_service
      build:
        context: .
        dockerfile: ./ApiUserService/Dockerfile  
      ports:
        - '8801:80'  
      # depends_on:
      #   - consulserver   

    product_service:
      image: product_service
      hostname: product_service
      environment:
       - ASPNETCORE_URLS=http://0.0.0.0:80
       - ConsulUrl=http://consulserver:8500
       - RegisterServerUrl=http://user_service
       - RegisterServiceName=product_service
      build:
        context: .
        dockerfile: ./ApiProductService/Dockerfile  
      ports:
        - '8802:80' 
       
      depends_on:
        - consulserver

    identity_service:
      image: identity_service
      hostname: identity_service
      build:
        context: .
        dockerfile: ./IdentityServer/Dockerfile  
      ports:
        - '8010:80' 

    ocelotgateway:
      image: ocelotgateway
      environment:
       - IdentityServerUrl=http://identity_service
      
      build:
        context: .
        dockerfile: ./ApiGateWayApp/Dockerfile  
      ports:
        - '80:80'  
      depends_on:
        - consulserver
        - user_service
        - product_service
        - identity_service

    simpleclient:
      image: simpleclient
      build:
        context: .
        dockerfile: ./Client/SimpleClient/Dockerfile  
      environment:
        - IdentityServerUrl=http://identity_service
        - GatewayUrl=http://ocelotgateway
      ports:
        - '8821:80'   
      depends_on:
        - ocelotgateway
        - user_service
        - product_service

      